
os: linux
services:
   - docker
sudo: required
language: python
env:
  matrix:
    - DOCKER_IMAGE=conanio/gcc64
    - DOCKER_IMAGE=conanio/gcc72
    - DOCKER_IMAGE=conanio/gcc8
    - DOCKER_IMAGE=conanio/clang39
    - DOCKER_IMAGE=conanio/clang40
    - DOCKER_IMAGE=conanio/clang50
    - DOCKER_IMAGE=conanio/clang60
    - DOCKER_IMAGE=conanio/clang7

matrix:
   include:

      - os: osx
        osx_image: xcode9.3
        language: generic
        addons:
          homebrew:
            packages:
            - pyenv-virtualenv
            - cmake
            - gcc
            - ninja
            - conan
            update: true

      - os: osx
        osx_image: xcode9.4
        language: generic
        addons:
          homebrew:
            packages:
            - pyenv-virtualenv
            - cmake
            - gcc
            - ninja
            - conan
            update: true

install:
  - chmod +x .travis/install.sh
  - travis_wait 30 ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - chmod +x .travis/run_project_build.sh
  - ./.travis/run.sh
